import = [
  "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
startup_mode = "Maximized"
option_as_alt = "Both"
opacity = 0.9

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true
